create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz not null default now()
);

create table if not exists public.search_history (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  query text not null,

  region text not null default 'BR',

  year text not null default 'ALL',

  order_by text not null default 'relevance',

  total_results integer not null default 0,

  search_type text not null default 'videos',

  created_at timestamptz not null default now()
);


-- Migração: bancos criados com a versão anterior não têm a coluna search_type
alter table public.search_history
  add column if not exists search_type text not null default 'videos';

create index if not exists profiles_email_idx
  on public.profiles(email);

create index if not exists search_history_user_created_idx
  on public.search_history(user_id, created_at desc);


alter table public.profiles enable row level security;
alter table public.search_history enable row level security;


drop policy if exists "Users can read own profile"
on public.profiles;

create policy "Users can read own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);


drop policy if exists "Users can insert own profile"
on public.profiles;

create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);


drop policy if exists "Users can update own profile"
on public.profiles;

create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);


drop policy if exists "Users can read own search history"
on public.search_history;

create policy "Users can read own search history"
on public.search_history
for select
to authenticated
using (auth.uid() = user_id);


drop policy if exists "Users can insert own search history"
on public.search_history;

create policy "Users can insert own search history"
on public.search_history
for insert
to authenticated
with check (auth.uid() = user_id);


drop policy if exists "Users can delete own search history"
on public.search_history;

create policy "Users can delete own search history"
on public.search_history
for delete
to authenticated
using (auth.uid() = user_id);


create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    full_name,
    avatar_url,
    created_at,
    updated_at,
    last_login_at
  )
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      'Usuário'
    ),
    coalesce(
      new.raw_user_meta_data->>'avatar_url',
      new.raw_user_meta_data->>'picture'
    ),
    now(),
    now(),
    now()
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created
on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

create or replace function public.handle_user_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
  set
    email = new.email,
    full_name = coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      full_name
    ),
    avatar_url = coalesce(
      new.raw_user_meta_data->>'avatar_url',
      new.raw_user_meta_data->>'picture',
      avatar_url
    ),
    updated_at = now()
  where id = new.id;

  return new;
end;
$$;

drop trigger if exists on_auth_user_updated
on auth.users;

create trigger on_auth_user_updated
after update on auth.users
for each row
execute procedure public.handle_user_update();

grant select, insert, update
on public.profiles
to authenticated;

grant select, insert, delete
on public.search_history
to authenticated;
