create table if not exists public.search_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  region text not null default 'BR',
  year text not null default 'ALL',
  order_by text not null default 'relevance',
  total_results integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists search_history_user_created_idx
  on public.search_history (user_id, created_at desc);

alter table public.search_history enable row level security;

drop policy if exists "Users can read own search history" on public.search_history;
drop policy if exists "Users can insert own search history" on public.search_history;
drop policy if exists "Users can delete own search history" on public.search_history;

create policy "Users can read own search history"
on public.search_history
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own search history"
on public.search_history
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can delete own search history"
on public.search_history
for delete
to authenticated
using (auth.uid() = user_id);

grant select, insert, delete on public.search_history to authenticated;
